/*
 * Copyright (c) 2021-2022, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
#ifndef REALM_PAYLOAD_TEST_H
#define REALM_PAYLOAD_TEST_H

#define NUM_GRANULES			5U
#define NUM_RANDOM_ITERATIONS		7U
#define B_DELEGATED			0U
#define B_UNDELEGATED			1U
#define NUM_CPU_DED_SPM			PLATFORM_CORE_COUNT / 2U

#define SIMD_NS_VALUE 			0x11
#define SIMD_REALM_VALUE 		0x33
#define SIMD_SECURE_VALUE 		0x22
#define FPCR_NS_VALUE 			0x7FF9F00
#define FPCR_REALM_VALUE 		0x75F9500
#define FPCR_SECURE_VALUE 		0x78F9900
#define FPSR_NS_VALUE 			0xF800009F
#define FPSR_REALM_VALUE 		0x88000097
#define FPSR_SECURE_VALUE 		0x98000095

/*SVE*/
#define SVE_Z_NS_VALUE			0x44
#define SVE_Z_REALM_VALUE		0x55
#define SVE_Z_SECURE_VALUE		0x66

#define SVE_P_NS_VALUE			0x77
#define SVE_P_REALM_VALUE		0x88
#define SVE_P_SECURE_VALUE		0x99

#define SVE_FFR_NS_VALUE		0xaa
#define SVE_FFR_REALM_VALUE		0xbb
#define SVE_FFR_SECURE_VALUE		0xcc

#define FPCR_NS_VALUE			0x7FF9F00
#define FPCR_REALM_VALUE		0x75F9500
#define FPCR_SECURE_VALUE		0x78F9900
#define FPSR_NS_VALUE			0xF800009F
#define FPSR_REALM_VALUE		0x88000097
#define FPSR_SECURE_VALUE		0x98000095


typedef enum realm_test_cmd {
	CMD_SIMD_NS_FILL = 0U,
	CMD_SIMD_NS_CMP,
	CMD_SIMD_SEC_FILL,
	CMD_SIMD_SEC_CMP,
	CMD_SIMD_RL_FILL,
	CMD_SIMD_RL_CMP,
	CMD_SVE_NS_FILL,
	CMD_SVE_NS_CMP,
	CMD_SVE_SEC_FILL,
	CMD_SVE_SEC_CMP,
	CMD_SVE_RL_FILL,
	CMD_SVE_RL_CMP,
	CMD_MAX_COUNT
} realm_test_cmd_t;

#endif
