/*
 * Copyright (c) 2024, Arm Limited. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef ARG_STRUCT_DEF_H
#define ARG_STRUCT_DEF_H

#define FUZZER_MAX_ARG_DEF 16

#define SDEI_EVENT_STATUS_CALL 0
#define SDEI_INTERRUPT_BIND_CALL 1
#define MAX_SMC_CALLS 1

#define SDEI_EVENT_STATUS_ARG0 0
#define SDEI_INTERRUPT_BIND_ARG0 1
#define MAX_ARG_LENGTH 1

#define SDEI_EVENT_STATUS_ARG0_BEV 0
#define SDEI_INTERRUPT_BIND_INUM 0
#define SDEI_EVENT_STATUS_ARG0_NFIELDS 1
#define SDEI_INTERRUPT_BIND_ARG0_NFIELDS 1

#endif /* ARG_STRUCT_DEF_H */

